### ISSUE TITLE
User review the Spring MVC guide

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/draft-guide-springboot-mvc#16]
## Timing
Took around 18 minutes to complete the guide.

## Overall Review
This guide is very straight forward and mostly informative. User was able to follow the instructions and explanations. There are a few suggestions:
- [ ] Maybe still include a short description of what Spring MVC is and how is it different from Open Liberty, so that user would know they are migrating a Spring Boot MVC Application to Open Liberty.

### Getting Started
- [x] the sentence “You’ll see from the page output that the `name` request parameter was received and handled” is unclear to user.

#### Changing the packaging type
- [x] "so add `<packaging>liberty-assembly</packaging>` near the top of the POM", "near the top" is considered to be vague and user might get confused, the position of the code should be clarified, maybe write something like underneath the `<version>1.0-SNAPSHOT</version>`
- [ ] The format for presenting the code different, I had to select the code and copy it manually instead of click the copy button. 

#### Adding POM properties
- [x] Instead of copy the whole block of properties, maybe just copy the one needed to add and tell the user to add it, for example: underneath java property, since what the `pom.xml` file would look like is posted below.

#### Adding and modifying dependencies
- [x] Specify the location of dependency: it is under dependencies block, so user don't accidentally remove the `<dependencies>` block and cause errors later on.

#### Adding the Liberty Maven Plugin
- [x] Specify the location of the plugin, example: inside `build` and `plugins`,  just to be perfectly clear to the audience.

**Comment by evelinec** [comment]
@yeekangc and @chyt FYI above user test feedback for your awareness about the instruction styles in this guide. I'll try to address them today.

**Comment by yeekangc** [comment]
Ref the 1st comment:  Spring MVC is an application.  Open Liberty is a runtime.  One is like an apple while the other is like the basket to carry apples.  They can't be compared since they are different in nature.

Sounds like what we need to do is to make clear that this is about running your Spring MVC or a sample Spring application on Open Liberty (instead of Tomcat, which is the server used by default).

**Comment by evelinec** [comment]
Regarding the following point, we're intended to keep the guide concise where there's one line of code, it will be included in the line of text instead of a code snippet/box where there can be copy function. If you really think this is a problem, we can adjust. Thanks.

- The format for presenting the code different, I had to select the code and copy it manually instead of click the copy button.

**Comment by yeekangc** [comment]
I am not sure what exactly this refers to but my 2 cents are that we should present consistently for user experience and as what we do in general, it is copy whole file over snippets.

**Comment by evelinec** [comment]
Checked with @Rachelwrq regarding the fixes for the user testing feedback. She's good. Closed.
