### ISSUE TITLE
Peer/Content Review

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-springboot-mvc#3]
- “First....you will remove the embedded Tomcat container.” 
Is that the first step? how? Don't see how in this guide?

- "Modifying the POM"
  better to start with this section by saying "navigating to the `...path/pom.xml` file ..."

- "You can also remove the spring-boot-devtools dependency." 
Why? What gonna happen if I remove it, or if I don't remove it?

- "Create a file called server.xml and place it in src/test/resources"
In order to keep consistent with other guides, say "Create a `src/test/resources/server.xml` server configuration file"

- "Traditionally, a Spring Boot application running on an embedded server such as Tomcat simply calls SpringApplication.run(…​) in its main class (in this case hello.Application). However, your class needs to extend SpringBootServletInitializer instead when being deployed to an Open Liberty server. Replace the original class with the following code:"
You didn't mention which file to open to change code. 

- "You will notice the same output as in the starting application."
 what is the starting application? Please be specific. You've already changed the starting application at this point. 

- No license. Neither the LICENSE file, nor license in the beginning of each file.

**Comment by chyt** [comment]
> “First....you will remove the embedded Tomcat container.”
Is that the first step? how? Don't see how in this guide?

I describe this in the "Add and modify dependencies" section. We exclude `spring-boot-starter-tomcat`. 

> "Modifying the POM"
better to start with this section by saying "navigating to the ...path/pom.xml file ..."

Done.

> "You can also remove the spring-boot-devtools dependency."
Why? What gonna happen if I remove it, or if I don't remove it?

It is an optional dependency. If it is on the classpath certain development features are enabled. But this is not relevant since this guide is about migrating an existing application. 

> "Create a file called server.xml and place it in src/test/resources"
In order to keep consistent with other guides, say "Create a src/test/resources/server.xml server configuration file"

Done. 

> "Traditionally, a Spring Boot application running on an embedded server such as Tomcat simply calls SpringApplication.run(…​) in its main class (in this case hello.Application). However, your class needs to extend SpringBootServletInitializer instead when being deployed to an Open Liberty server. Replace the original class with the following code:"
You didn't mention which file to open to change code.

I give the class name: `hello.Application`. 

> "You will notice the same output as in the starting application."
what is the starting application? Please be specific. You've already changed the starting application at this point.

The starting application is described in the `Running the starting application in embedded Tomcat` section. 

> No license. Neither the LICENSE file, nor license in the beginning of each file.

Added the license.
